### ISSUE TITLE
Reserved keyword names cause compilation errors.

### ISSUE THREAD

**Issue by jelmersnoeck** [jbowes/oag#23]
When using a reserved keyword as an argument name, it will cause compilation errors.

```yaml
  /users:
    get:
      summary: List users
      parameters:
        - name: type
          in: query
          type: string
          enum: [api]
          required: true
```

This tries to make the following `List` function:

```go
… List(ctx context.Context, type string, …) …
````

This causes the compiler to fail seeing that `type` is a reserved keyword.
